version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn --version

  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package
  post_build:
    commands:
      - echo Build, Testing and packaging completed.
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
